In [8]:
import pandas as pd

dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')
dataFrame.dtypes
len(dataFrame)
dataFrame.info()

<class 'pandas.DataFrame'>
RangeIndex: 376 entries, 0 to 375
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statistic_yyy       371 non-null    str
 1   site_id             375 non-null    str
 2   people_total        371 non-null    str
 3   area                371 non-null    str
 4   population_density  371 non-null    str
dtypes: str(5)
memory usage: 28.5 KB

In [26]:
import pandas as pd
dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')

dataFrame.columns = ["統計年", "區域別", "年底人口數", "土地面積", "人口密碼"] #改變欄位名稱
df = dataFrame.drop(index=0)
df

,統計年,區域別,年底人口數,土地面積,人口密碼
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
5,106,新北市新莊區,416524,19.7383,21102
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

In [36]:
import pandas as pd
dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')

dataFrame.columns = ['統計年', '區域別', '年底人口數', '土地面積', '人口密度'] #改變欄位名稱
df = dataFrame.drop(index=0) #刪除第一行
df1 = df.dropna() #刪除缺失值
df2 = df1.drop('統計年', axis=1) #刪除'統計年'欄位

df2

        區域別   年底人口數     土地面積   人口密度
1    新北市板橋區  551480  23.1373  23835
2    新北市三重區  387484   16.317  23747
3    新北市中和區  413590   20.144  20532
4    新北市永和區  222585   5.7138  38956
5    新北市新莊區  416524  19.7383  21102
..      ...     ...      ...    ...
366  連江縣北竿鄉    2360      9.9    238
367  連江縣莒光鄉    1624      4.7    346
368  連江縣東引鄉    1352      3.8    356
369    東沙群島      …      2.38     …
370    南沙群島      …    0.5045     …

[370 rows x 4 columns]

In [40]:
import pandas as pd
dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')

dataFrame.columns = ['統計年', '區域別', '年底人口數', '土地面積', '人口密度'] #改變欄位名稱
df = dataFrame.drop(index=0) #刪除第一行
df1 = df.dropna() #刪除缺失值
df2 = df1.drop('統計年', axis=1) #刪除'統計年'欄位
df4 = pd.to_numeric(dataFrame['年底人口數'], errors='coerce') # 將'年底人口數'欄位轉換為數值型態，無法轉換的值將被設為NaN
df5 = df4.dropna()

df3 = df2.copy() # 建立 df2 的副本，避免直接修改原始資料
df3['年底人口數'] = pd.to_numeric(df3['年底人口數'], errors='coerce') # 安全轉換法：轉換成數字，如果遇到無法轉換的文字會先變成 NaN
df3['年底人口數'] = df3['年底人口數'].astype(int) # 確保轉為整數型態 (int)
print(df3['年底人口數'].dtype) # 檢查轉換後的資料型態（會顯示 int64）

df3

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')